openapi: 3.0.0
security: []
info:
  title: Fundamental Stocks API
  description: Add, remove, add notes to watched stocks
  version: 1.0.0
servers:
  - url: http://localhost:5173
    description: user data
paths:
  /stocks:
    $ref: paths/stocks.yml
  /stocks/{symbol}:
    $ref: paths/add-note.yml
  /stocks/{symbol}/{noteId}:
    $ref: paths/delete-note.yml
  /market-data/quote:
    $ref: paths/get-quote.yml
  /market-data/price:
    $ref: paths/get-price.yml
  /market-data/time-series:
    $ref: paths/get-time-series.yml
  /market-data/income-statement:
    $ref: paths/get-income-statement.yml
